A fetch() promise only rejects when a network error is encountered

*Good to know*
- [fetch Exceptions](https://developer.mozilla.org/en-US/docs/Web/API/fetch#exceptions)
- [Request cache property](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache)
- [Request mode property](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode)
- [Request credentials property](https://developer.mozilla.org/en-US/docs/Web/API/fetch#credentials)